export const FamousPeople =  [
    { name: "Albert Einstein", hints: ["I developed the theory of relativity. Let’s break this down to the atomic level… Say my name.",
      "Born in Germany. Nobel Prize in Physics, 1921. E = mc² wasn’t just a formula—it was a revolution."] },
    { name: "Leonardo da Vinci", hints: ["I painted a mysterious smile and imagined machines before they were possible. Who am I?",
      "Renaissance wasn’t a period. It was me. Art, anatomy, flight—I did it all. Say my name."] },
    { name: "Isaac Newton", hints: ["Let’s cook… up some knowledge. Ready?. An apple fell. Gravity didn’t. I wrote the laws you still live by. Who am I?",
      "Motion. Force. Optics. I gave the universe rules—and you’re still catching up. Say my name."] },
    { name: "Charles Darwin", hints: ["Natural selection wasn’t luck. It was science. I evolved the way we see life. Who am I?",
      "*Origin of Species*. I didn’t just adapt—I redefined biology. Say my name."] },
    { name: "Shakespeare", hints: ["To be or not to be? I wrote the question—and the tragedy that followed. Who am I?",
      "The Bard. The Globe. The quill behind every drama you’ve ever copied. Say my name."] },
    { name: "Mary Shelley", hints: ["I created life… on paper. My monster had no name, but I do. Who am I?",
      "Call it gothic, call it sci-fi—I wrote it first. Storm, fear, and ink. Say my name."] },
    { name: "Frida Kahlo", hints: ["Pain was my palette. My face was my canvas. Who am I?",
      "Diego was loud. My art? Louder. Every color screams my truth. Say my name."] },
    { name: "Rosa Parks", hints: ["One bus. One choice. I sat down so the movement could stand up. Who am I?",
      "They told me to move. I didn’t. And history moved instead. Say my name."] },
    { name: "Grace Hopper", hints: ["I taught machines how to speak human. Code, compiled. Problems, debugged. Who am I?",
      "Rear Admiral. Pioneer. I turned logic into language—and named the first bug. Say my name."] },
    { name: "Ada Lovelace", hints: ["Before computers existed, I wrote the algorithm that started it all. Who am I?",
      "I saw machines not as tools—but as thinkers. First coder. First visionary. Say my name."] },
  ];