export const FamousPeople =  [
    { name: "Albert Einstein", hints: ["Let’s break this down to the atomic level.", "He developed the theory of relativity.", "E = mc²"] },
    { name: "Walter White", hints: ["Say my name.", "I am the one who knocks.", "Let's cook."] },
    { name: "Marie Curie", hints: ["She discovered radioactivity.", "She was the first woman to win a Nobel Prize.", "She worked with radium and polonium."] },
    { name: "Leonardo da Vinci", hints: ["He painted the Mona Lisa.", "He was also an inventor and scientist.", "He lived during the Renaissance."] },
    { name: "Santos Dumont", hints: ["He was a pioneer in aviation.", "He created the first airplane.", "He created the wrist watch that was named after him, Cartier Santos-Dumont."] },
    { name: "Isaac Newton", hints: ["He formulated the laws of motion.", "He discovered gravity.", "He wrote 'Principia Mathematica'."] },
    { name: "Nikola Tesla", hints: ["He worked with electricity.", "He was known for alternating current (AC).", "He had a rivalry with Thomas Edison."] },
    { name: "Charles Darwin", hints: ["He developed the theory of evolution.", "He wrote 'On the Origin of Species'.", "He traveled on the HMS Beagle."] },
    { name: "Pelé", hints: ["He was a Brazilian footballer.", "He won the Ballon d'Or in 1962.", "He played for the Brazil national team."] },
    { name: "Shakespeare", hints: ["He wrote 'Romeo and Juliet'.", "He was an English playwright.", "He lived during the Elizabethan era."] },
    { name: "Paulo Coelho", hints: ["He is a Brazilian novelist'.", "His most famous book is The Alchemist.", "He often writes about self-discovery and personal legends."] },
    { name: "Mary Shelley", hints: ["She wrote Frankenstein.", "She is considered one of the first science fiction novels.", "Her contributions to literature influenced the Gothic and horror genres."] },
    { name: "Frida Kahlo", hints: ["She painted many self-portraits.", "She was severely injured in a bus accident, which influenced her art.","She was married to the Mexican muralist Diego Rivera."] },
    { name: "Tom Jobim", hints: ["He was one of the creators of Bossa Nova music.", "He composed 'Garota de Ipanema' or 'The Girl from Ipanema'.", "His music blended Brazilian rhythms with jazz influences."] },
    { name: "Rosa Parks", hints: ["She refused to give up her bus seat in Montgomery, Alabama.", "She is responsible for an act of defiance which became a key moment in the Civil Rights Movement.", "She worked with Martin Luther King Jr. to fight racial segregation."] },
    { name: "Grace Hopper", hints: ["She was a U.S. Navy Rear Admiral and a pioneer in computer programming.", "She developed the first compiler for a programming language.","She popularized the term 'debugging' after removing a moth from a computer."] },
    { name: "Ada Lovelace", hints: ["She was one of the first programmers.", "She is considered the first computer programmer.", "She was a mathematician and writer."] },
    { name: "Fernanda Torres", hints: ["She is a Brazilian actress.", "She won a Golden Globe Award for Best Actress in 2025.", "The movie she plays the main character won an Oscar for best international movie in 2025."] },
  ];