export const stopGameNow = [
    {stopping: "stop"},
    {stopping: "stop game now"},
    {stopping: "stop game"},
    {stopping: "stop now"},
    {stopping: "end the game"},
    {stopping: "exit the game"},
    {stopping: "quit the game"},
    {stopping: "exit the conversation"},
    {stopping: "end the conversation"},
    {stopping: "finish the conversation"},
    {stopping: "end this conversation"},
    {stopping: "close the conversation"},
    {stopping: "end this session"},
    {stopping: "quit this session"},
    {stopping: "leave the conversation"},
    {stopping: "exit the chat"},
    {stopping: "quit the chat"},
    {stopping: "leave the chat"},
    {stopping: "end the chat"},
    {stopping: "close the chat"},
  ];